### ISSUE TITLE
JSON Example from RML Specs not working

### ISSUE THREAD

**Issue by noorbakerally** [RMLio/RML-Mapper#1]
I was going through the RML Specs and i tried the examples found at the beginning of the the Specs Document at http://rml.io/spec.html. 

I created a small github repo for the examples at https://github.com/noorbakerally/rml-examples. 

Status:
1. The CSV example is working
2. The XML example is NOT working. It is complaining about invalid XPath
3. The JSON mapping completes but with 0 tripples generated.

For the JSON example, I used the following command

java -jar RML-mapper.jar -m venue.rml.ttl -o venue.rdf

The commands executes and completes without any error. But the venue.rdf generated is empty. The output of the command is found below:

---
## RML Processor

1 [main] INFO be.ugent.mmlab.rml.main.Main  - ========================================
1 [main] INFO be.ugent.mmlab.rml.main.Main  - Retrieving the RML Mapping Document...
1 [main] INFO be.ugent.mmlab.rml.main.Main  - ========================================
13 [main] DEBUG org.openrdf.sail.memory.MemoryStore  - Initializing MemoryStore...
19 [main] DEBUG org.openrdf.sail.memory.MemoryStore  - MemoryStore initialized
43 [main] DEBUG org.openrdf.rio.RDFParserRegistry  - Registered service class org.openrdf.rio.trig.TriGParserFactory
44 [main] DEBUG org.openrdf.rio.RDFParserRegistry  - Registered service class org.openrdf.rio.turtle.TurtleParserFactory
44 [main] DEBUG org.openrdf.rio.RDFParserRegistry  - Registered service class org.openrdf.rio.ntriples.NTriplesParserFactory
44 [main] DEBUG org.openrdf.rio.RDFParserRegistry  - Registered service class org.openrdf.rio.binary.BinaryRDFParserFactory
45 [main] DEBUG org.openrdf.rio.RDFParserRegistry  - Registered service class org.openrdf.rio.n3.N3ParserFactory
45 [main] DEBUG org.openrdf.rio.RDFParserRegistry  - Registered service class org.openrdf.rio.trix.TriXParserFactory
45 [main] DEBUG org.openrdf.rio.RDFParserRegistry  - Registered service class org.openrdf.rio.rdfxml.RDFXMLParserFactory
46 [main] DEBUG org.openrdf.rio.RDFParserRegistry  - Registered service class org.openrdf.rio.nquads.NQuadsParserFactory
46 [main] DEBUG org.openrdf.rio.RDFParserRegistry  - Registered service class org.openrdf.rio.rdfjson.RDFJSONParserFactory
46 [main] DEBUG org.openrdf.rio.RDFParserRegistry  - Registered service class org.openrdf.rio.jsonld.JSONLDParserFactory
64 [main] DEBUG org.openrdf.rio.DatatypeHandlerRegistry  - Registered service class org.openrdf.rio.datatypes.XMLSchemaDatatypeHandler
65 [main] DEBUG org.openrdf.rio.DatatypeHandlerRegistry  - Registered service class org.openrdf.rio.datatypes.RDFDatatypeHandler
65 [main] DEBUG org.openrdf.rio.DatatypeHandlerRegistry  - Registered service class org.openrdf.rio.datatypes.DBPediaDatatypeHandler
65 [main] DEBUG org.openrdf.rio.DatatypeHandlerRegistry  - Registered service class org.openrdf.rio.datatypes.VirtuosoGeometryDatatypeHandler
66 [main] DEBUG org.openrdf.rio.DatatypeHandlerRegistry  - Registered service class org.openrdf.rio.datatypes.GeoSPARQLDatatypeHandler
68 [main] DEBUG org.openrdf.rio.LanguageHandlerRegistry  - Registered service class org.openrdf.rio.languages.RFC3066LanguageHandler
99 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.retrieval.RMLDocRetrieval  - Number of RML triples in the repository venue.rml.ttl : 19 from local file
100 [main] INFO be.ugent.mmlab.rml.main.Main  - ========================================
100 [main] INFO be.ugent.mmlab.rml.main.Main  - Extracting the RML Mapping Definitions..
100 [main] INFO be.ugent.mmlab.rml.main.Main  - ========================================
100 [main] INFO be.ugent.mmlab.rml.mapdochandler.extraction.RMLMappingFactory  - Replacing Mapping Document shortcuts..
107 [main] INFO be.ugent.mmlab.rml.mapdochandler.extraction.RMLMappingFactory  - Extracting Triples Maps..
107 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.std.StdRMLMappingExtractor  - Triples Map statements were retrieved: true
108 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.RMLMappingFactory  - Number of RML triples with type TriplesMap in file: 1
109 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TriplesMapExtractor  - Extract TriplesMap subject : file:/home/bakerally/Documents/project/test/rml-mapper/rml-examples/venue.rml.ttl#VenueMapping
112 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TriplesMapExtractor  - Reference Formulation JSONPath
112 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TriplesMapExtractor  - Iterator $
113 [main] INFO be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TriplesMapExtractor  - Literal-valued Input Source
115 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TriplesMapExtractor  - Query null
115 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TriplesMapExtractor  - Triples Map extracted
115 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TriplesMapExtractor  - Logical source extracted : [StdLogicalSource : iterator = $; source be.ugent.mmlab.rml.model.source.std.StdLocalFileSource@3f2a3a5; referenceFormulation = JSONPath]
116 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.SubjectMapExtractor  - Extract subject map...
116 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.SubjectMapExtractor  - Found subject map : node1a8k873h0x2
117 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - extractLiteralFromTermMap: Extracted template : http://loc.example.com/city/{$.location.city}
118 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - referenceValueStr null
118 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - refMap.getReferenceValue(referenceValueStr) null
118 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - extractURIsFromTermMap: class : http://schema.org/City
119 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.SubjectMapExtractor  - Graph Maps returned []
121 [main] DEBUG be.ugent.mmlab.rml.model.RDFTerm.AbstractTermMap  - setTermType: [AbstractTermMap:setTermType] No term type specified : use IRI by default.null
122 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.SubjectMapExtractor  - Subject map extracted.
124 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - More Predicate Map statements: true
124 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - Extracted constant : http://www.w3.org/2003/01/geo/wgs84_pos#latlat
125 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - referenceValueStr null
125 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - refMap.getReferenceValue(referenceValueStr) null
125 [main] DEBUG be.ugent.mmlab.rml.model.RDFTerm.AbstractTermMap  - setTermType: [AbstractTermMap:setTermType] No term type specified : use IRI by default.null
126 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateMapExtractor  - Extracting predicate map done.
126 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Object Map statements found: org.openrdf.repository.RepositoryResult@ae45eb6
126 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Extracting Referencing Object Maps..
126 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Extracting Referencing Object Map..
127 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Parent Triples Maps were found null
127 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Extract join conditions..
127 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Extract join conditions done.
128 [main] DEBUG be.ugent.mmlab.rml.condition.extractor.BindingConditionExtractor  - Extracting Binding Conditions..
128 [main] DEBUG be.ugent.mmlab.rml.condition.extractor.BindingConditionExtractor  - Extract bind condition done.
128 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Current Triples Map resource file:/home/bakerally/Documents/project/test/rml-mapper/rml-examples/venue.rml.ttl#VenueMapping
128 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Not a Referencing Object Map.
128 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Referencing Object Map statements found: []
129 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ObjectMapExtractor  - Extract object map..
130 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - extractLiteralFromTermMap: Extracted reference : $.venue.latitude
130 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - referenceValueStr $.venue.latitude
130 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - refMap.getReferenceValue(referenceValueStr) be.ugent.mmlab.rml.model.std.StdReferenceMap@5702b3b1
130 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ObjectMapExtractor  - reference value be.ugent.mmlab.rml.model.std.StdReferenceMap@69ea3742
130 [main] DEBUG be.ugent.mmlab.rml.model.RDFTerm.AbstractTermMap  - setTermType: [AbstractTermMap:setTermType] No term type specified : use Literal by default.
131 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.GraphMapExtractor  - Gtraph Maps returned []
131 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Extract predicate-object map done.
131 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - More Predicate Map statements: true
131 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - Extracted constant : http://www.w3.org/2003/01/geo/wgs84_pos#latlong
132 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - referenceValueStr null
132 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - refMap.getReferenceValue(referenceValueStr) null
132 [main] DEBUG be.ugent.mmlab.rml.model.RDFTerm.AbstractTermMap  - setTermType: [AbstractTermMap:setTermType] No term type specified : use IRI by default.null
132 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateMapExtractor  - Extracting predicate map done.
132 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Object Map statements found: org.openrdf.repository.RepositoryResult@335eadca
132 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Extracting Referencing Object Maps..
132 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Extracting Referencing Object Map..
132 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Parent Triples Maps were found null
132 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Extract join conditions..
133 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Extract join conditions done.
133 [main] DEBUG be.ugent.mmlab.rml.condition.extractor.BindingConditionExtractor  - Extracting Binding Conditions..
133 [main] DEBUG be.ugent.mmlab.rml.condition.extractor.BindingConditionExtractor  - Extract bind condition done.
133 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Current Triples Map resource file:/home/bakerally/Documents/project/test/rml-mapper/rml-examples/venue.rml.ttl#VenueMapping
133 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Not a Referencing Object Map.
133 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Referencing Object Map statements found: []
133 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ObjectMapExtractor  - Extract object map..
134 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - extractLiteralFromTermMap: Extracted reference : $.venue.longitude
134 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - referenceValueStr $.venue.longitude
134 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - refMap.getReferenceValue(referenceValueStr) be.ugent.mmlab.rml.model.std.StdReferenceMap@5d76b067
134 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ObjectMapExtractor  - reference value be.ugent.mmlab.rml.model.std.StdReferenceMap@2a17b7b6
134 [main] DEBUG be.ugent.mmlab.rml.model.RDFTerm.AbstractTermMap  - setTermType: [AbstractTermMap:setTermType] No term type specified : use Literal by default.
134 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.GraphMapExtractor  - Gtraph Maps returned []
134 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Extract predicate-object map done.
134 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - More Predicate Map statements: true
135 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - Extracted constant : http://www.geonames.org/ontology#countryCode
136 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - referenceValueStr null
136 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - refMap.getReferenceValue(referenceValueStr) null
136 [main] DEBUG be.ugent.mmlab.rml.model.RDFTerm.AbstractTermMap  - setTermType: [AbstractTermMap:setTermType] No term type specified : use IRI by default.null
136 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateMapExtractor  - Extracting predicate map done.
136 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Object Map statements found: org.openrdf.repository.RepositoryResult@458c1321
136 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Extracting Referencing Object Maps..
136 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Extracting Referencing Object Map..
136 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Parent Triples Maps were found null
136 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Extract join conditions..
136 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Extract join conditions done.
136 [main] DEBUG be.ugent.mmlab.rml.condition.extractor.BindingConditionExtractor  - Extracting Binding Conditions..
137 [main] DEBUG be.ugent.mmlab.rml.condition.extractor.BindingConditionExtractor  - Extract bind condition done.
137 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Current Triples Map resource file:/home/bakerally/Documents/project/test/rml-mapper/rml-examples/venue.rml.ttl#VenueMapping
137 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ReferencingObjectMapExtractor  - Not a Referencing Object Map.
137 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Referencing Object Map statements found: []
137 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ObjectMapExtractor  - Extract object map..
138 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - extractLiteralFromTermMap: Extracted reference : $.location.country
138 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - referenceValueStr $.location.country
138 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TermMapExtractor  - refMap.getReferenceValue(referenceValueStr) be.ugent.mmlab.rml.model.std.StdReferenceMap@cb51256
138 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.ObjectMapExtractor  - reference value be.ugent.mmlab.rml.model.std.StdReferenceMap@59906517
138 [main] DEBUG be.ugent.mmlab.rml.model.RDFTerm.AbstractTermMap  - setTermType: [AbstractTermMap:setTermType] No term type specified : use Literal by default.
139 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.GraphMapExtractor  - Gtraph Maps returned []
139 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.PredicateObjectMapExtractor  - Extract predicate-object map done.
139 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TriplesMapExtractor  - Number of extracted predicate-object maps : 3
139 [main] DEBUG be.ugent.mmlab.rml.mapdochandler.extraction.concrete.TriplesMapExtractor  - Extract of TriplesMap subject : file:/home/bakerally/Documents/project/test/rml-mapper/rml-examples/venue.rml.ttl#VenueMapping done.
139 [main] INFO be.ugent.mmlab.rml.main.Main  - ========================================
139 [main] INFO be.ugent.mmlab.rml.main.Main  - Running the RML Mapping..
139 [main] INFO be.ugent.mmlab.rml.main.Main  - ========================================
139 [main] DEBUG be.ugent.mmlab.rml.core.RMLEngine  - Running RML mapping... 
139 [main] DEBUG be.ugent.mmlab.rml.core.RMLEngine  - Using direct file venue.rdf
140 [main] DEBUG org.openrdf.sail.memory.MemoryStore  - Initializing MemoryStore...
140 [main] DEBUG org.openrdf.sail.memory.MemoryStore  - MemoryStore initialized
142 [main] DEBUG org.openrdf.rio.RDFWriterRegistry  - Registered service class org.openrdf.rio.trig.TriGWriterFactory
142 [main] DEBUG org.openrdf.rio.RDFWriterRegistry  - Registered service class org.openrdf.rio.turtle.TurtleWriterFactory
143 [main] DEBUG org.openrdf.rio.RDFWriterRegistry  - Registered service class org.openrdf.rio.ntriples.NTriplesWriterFactory
143 [main] DEBUG org.openrdf.rio.RDFWriterRegistry  - Registered service class org.openrdf.rio.binary.BinaryRDFWriterFactory
143 [main] DEBUG org.openrdf.rio.RDFWriterRegistry  - Registered service class org.openrdf.rio.n3.N3WriterFactory
144 [main] DEBUG org.openrdf.rio.RDFWriterRegistry  - Registered service class org.openrdf.rio.trix.TriXWriterFactory
144 [main] DEBUG org.openrdf.rio.RDFWriterRegistry  - Registered service class org.openrdf.rio.rdfxml.RDFXMLWriterFactory
144 [main] DEBUG org.openrdf.rio.RDFWriterRegistry  - Registered service class org.openrdf.rio.nquads.NQuadsWriterFactory
144 [main] DEBUG org.openrdf.rio.RDFWriterRegistry  - Registered service class org.openrdf.rio.rdfjson.RDFJSONWriterFactory
145 [main] DEBUG org.openrdf.rio.RDFWriterRegistry  - Registered service class org.openrdf.rio.jsonld.JSONLDWriterFactory
146 [main] DEBUG be.ugent.mmlab.rml.core.RMLEngine  - Dataset repository generated
146 [main] DEBUG be.ugent.mmlab.rml.core.RMLEngine  - Generating triples..
146 [main] DEBUG be.ugent.mmlab.rml.core.RMLEngine  - Generate RDF triples... 
Generating RDF triples for file:/home/bakerally/Documents/project/test/rml-mapper/rml-examples/venue.rml.ttl#VenueMapping
146 [main] INFO be.ugent.mmlab.rml.core.RMLEngine  - Generating RML Processor..
147 [main] DEBUG be.ugent.mmlab.rml.core.RMLEngine  - Logical Source: [StdLogicalSource : iterator = $; source be.ugent.mmlab.rml.model.source.std.StdLocalFileSource@3f2a3a5; referenceFormulation = JSONPath]
147 [main] DEBUG be.ugent.mmlab.rml.core.RMLEngine  - Reference formulation: JSONPath
150 [main] INFO be.ugent.mmlab.rml.core.RMLEngine  - Generating Data Retrieval Processor..
150 [main] DEBUG be.ugent.mmlab.rml.input.ConcreteLogicalSourceProcessorFactory  - Resource-valued Input Source
150 [main] DEBUG be.ugent.mmlab.rml.input.ConcreteLogicalSourceProcessorFactory  - source type StdLocalFileSource
150 [main] DEBUG be.ugent.mmlab.rml.input.ConcreteLogicalSourceProcessorFactory  - Processor for Local File Source.
151 [main] DEBUG be.ugent.mmlab.rml.core.RMLEngine  - Generating Input Stream..
151 [main] DEBUG be.ugent.mmlab.rml.core.RMLEngine  - Generating Performer..
152 [main] DEBUG be.ugent.mmlab.rml.core.RMLEngine  - Executing Mapping Processor..
182 [main] DEBUG com.jayway.jsonpath.internal.CompiledPath  - Evaluating path: $
184 [main] INFO be.ugent.mmlab.rml.core.RMLEngine  - 0 triples were generated for file:/home/bakerally/Documents/project/test/rml-mapper/rml-examples/venue.rml.ttl#VenueMapping
184 [main] DEBUG be.ugent.mmlab.rml.core.RMLEngine  - Generating metadata..
184 [main] INFO be.ugent.mmlab.rml.core.RMLEngine  - RML mapping done! Generated 0 in 0.044516035s . 
184 [main] DEBUG be.ugent.mmlab.rml.model.dataset.FileDataset  - Closing file...

**Comment by andimou** [comment]
2. The problem with the XML is the quotes encoding at your xml file. It's a side effect from copy-pasting from the HTML. Change the quotes and it will work.

3. Regarding the JSON example and overall, you may advise the https://github.com/RMLio/RML-Processor/tree/master/src/test/resources where different examples are outlined, including the one you are trying.

**Comment by noorbakerally** [comment]
The things which concerns me is the JSON. As such, I've run example3 (https://github.com/RMLio/RML-Processor/tree/master/src/test/resources/example3) from RML Examples you gave me, 

I've performed the RML Mapping with the same mapping file example3.rml.ttl using the command "java -jar rml-mapper.jar -m example3.rml.ttl -o example3.output1.ttl".

The output file example3.output1.ttl is completely different from the given output example3.output.ttl though the very same mapping file has been used with the same sources. 

In fact, no tripples is being generated from the VenueMapping trippleMap whose source is a json

**Comment by andimou** [comment]
Firstly, the examples you see are unit tests for the RML-Processor. That being said, the jar for the RML-Mapper can not be generated if the examples do not generate proper output. So, the example 3 returns the expected output so it is correct.

Moreover, I just tried it locally and using the command java -jar target/RML-Processor-0.2.jar -m /home/andimou/RML-Mapper/RML-Processor/src/test/resources/example3/example3.rml.ttl -o /home/andimou/RML/Output/norbakerally/example.ttl -f turtle

Could you copy-paste the exact command that you run?

**Comment by noorbakerally** [comment]
I understand that the generation cannot happen, but it's not generating the same output for me,

the command i'm using is java -jar /home/bakerally/Documents/tutorials/2016/rml/mapper/RML-Mapper/RML-Processor/target/RML-Processor-0.2.jar -m example3.rml.ttl -o example3.ttl -f turtle

You can see the generated output i'm getting at https://github.com/noorbakerally/rml-examples/tree/master/example3 which contains the exact example from the RML Processor,

**Comment by andimou** [comment]
Would you like to try example 4? It's the same and let me know what's going on?

**Comment by noorbakerally** [comment]
Example4 works fine but Example3 still doesn't work, The difference between Example3 and Example4 is the Input Source JSON Format, is there anything like it's tailored to a specific type of JSON Format ?

**Comment by andimou** [comment]
I noticed that example 3 is not included at the unit tests any more so consider it as deprecated.
If example 4 works for JSON files, I think you have examples running for all three cases (CSV, XML, JSON).

**Comment by noorbakerally** [comment]
In the Specs, at the beginning, 3 examples were given, 2 of them are not working making it confusing how to operate systemically,

Venue Example at beginning of Specs
=============================
In the github repo at https://github.com/noorbakerally/rml-examples/blob/master/venue_example, I replicated the JSON example given at the beginning and run it with the command 

java -jar /home/bakerally/Documents/tutorials/2016/rml/mapper/RML-Mapper/RML-Processor/target/RML-Processor-0.2.jar -m venue.rml.ttl -o venue.ttl -f turtle

It generated an empty file

Transport Example at the beginning of Specs
===================================
In https://github.com/noorbakerally/rml-examples/tree/master/transport_example, it's the same example given for the transport xml at the beginning of the specs,

java -jar /home/bakerally/Documents/tutorials/2016/rml/mapper/RML-Mapper/RML-Processor/target/RML-Processor-0.2.jar -m transport.rml.ttl -o transport.ttl

So right now, I'm big confused about the problems and how it works, i went through both documentation R2RML and RML, if these example work, I can proceed systemically and clear I can the confusions

do you have an idea about the problems ?

**Comment by noorbakerally** [comment]
I don't know if there is a problem with the JSON conversion, but there is an example you provided in slide  21 at http://www.slideshare.net/andimou/dimou-rdf-mappinglanguage?related=1, I replicated the example here https://github.com/noorbakerally/rml-examples/tree/master/stock, this example is also not working and generating an empty turtle file

**Comment by noorbakerally** [comment]
Any update about why the examples do not work or how to make them work ?

**Comment by pheyvaer** [comment]
Hi,

We've updated the RMLMapper and it can now be found [here](https://github.com/RMLio/rmlmapper-java). I've tried the example in your last comment and that generates RDF with the latest version of the RMLMapper. If you have still issues, you can open a new issue at the repo of the new RMLMapper.
