### ISSUE TITLE
RML Networking

### ISSUE THREAD

**Issue by alakhame** [RMLio/RML-Mapper#2]
Hello 

I am trying the sample example from the specfications in section 3.3 (3.3 Example: Mapping a JSON data source) but it is outputting an empty turtle file,

the commands i am using is:

 java -jar /home/apps/RML-Mapper/RML-Processor/target/RML-Processor-0.2.jar -m venue.json.rml.ttl -o venue.ttl -f turtle,

where venue.rml.ttl is sample mapping file given in section 3.3 of the specification. I am using exactly the same example as given in section 3.3 without changing anything,

Is there any problem with the command ?

**Comment by pheyvaer** [comment]
Hi,

We've updated the RMLMapper and it can now be found [here](https://github.com/RMLio/rmlmapper-java). If you still have issues, you can open a new issue at the repo of the new RMLMapper.
