### ISSUE TITLE
Slow execution times and too much debug output

### ISSUE THREAD

**Issue by setzer22** [RMLio/RML-Mapper#22]
Hello all,

I don't know if this is a current issue with the application or I just haven't found the feature. When mapping a JSON (an array of several hundred values) using RML-Mapper, I get very slow execution times and a lot of debug information is printed on the terminal. From that, I get the impression the tool is running in debug mode, is there a way I could use a more optimized mode that omits all the debug information for each mapped triple and, hopefully, runs faster? 

Right now I see the tool mapping around 5 JSON objects per second. I think I'm probably doing something wrong. If there is a feature for this, I would suggest for it to be added more clearly in the README documentation. Otherwise I think there should be a way to disable all that debug output.

Thank you for your help!

**Comment by pheyvaer** [comment]
Hi,

We've updated the RMLMapper and it can now be found [here](https://github.com/RMLio/rmlmapper-java). Now debug output is disabled by default and can be enabled via `-v` and the overall execution should be faster. If you have still issues, you can open a new issue at the repo of the new RMLMapper.
