### ISSUE TITLE
Transformation process misses CSV rows

### ISSUE THREAD

**Issue by nicky508** [RMLio/RML-Mapper#23]
I try to converted some large files. But when the transformation process is completed I miss objects in the turtle file. For example one of the files contain 25612 rows, but after the transformation only 15104 objects are created. This happens with multiple files and I cannot find a satisfying explanation why this happens.

**Comment by pheyvaer** [comment]
It could be that no subject is generated for those specific rows. Can you determine which rows are missing?

**Comment by pheyvaer** [comment]
Hi,

We've updated the RMLMapper and it can now be found [here](https://github.com/RMLio/rmlmapper-java). Due to inactivity of this issue we are closing it, but if you have still issues, you can open a new issue at the repo of the new RMLMapper.
