### ISSUE TITLE
RML accented characters

### ISSUE THREAD

**Issue by ShanzayA** [RMLio/RML-Mapper#24]
I have been having trouble mapping CSV fields containing accented characters (e.g. é). In the example attached, I have no problem mapping from the "Ref" field into triples, but any triples referencing from the "Créateur" field simply do not get created. Is there some character encoding that would help RML recognize accented or other special characters?
[ExampleProblem.txt](https://github.com/RMLio/RML-Mapper/files/1114611/ExampleProblem.txt)
[ExampleRML.txt](https://github.com/RMLio/RML-Mapper/files/1114615/ExampleRML.txt)

**Comment by p1d1d1** [comment]
Any news here? My issue is similar: I have accented chars as values. Not able to get a right encoding.

**Comment by pheyvaer** [comment]
@ShanzayA This is probably related to the library that we use to process CSV files. We will look into it and get back to you.

**Comment by pheyvaer** [comment]
Hi,

We've updated the RMLMapper and it can now be found [here](https://github.com/RMLio/rmlmapper-java). I've tried your example with latest version of the RMLMapper and it works. If you have still issues, you can open a new issue at the repo of the new RMLMapper.
