### ISSUE TITLE
Cannot get first field of a CSV

### ISSUE THREAD

**Issue by p1d1d1** [RMLio/RML-Mapper#26]
I'm not able to get values from the first field of a .csv

With these files: 
[map.txt](https://github.com/RMLio/RML-Mapper/files/1341484/map.txt)
[stops.txt](https://github.com/RMLio/RML-Mapper/files/1341485/stops.txt)

(rename map to map.ttl and stops to stops.csv)

I'm not able to get the "Long" field

**Comment by pheyvaer** [comment]
@p1d1d1 This happens because `stops.txt` has a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). This should be removed when using UTF-8. You can remove it via `sed -i '1s/^\xEF\xBB\xBF//' stops.txt` if you are working with Linux.

**Comment by p1d1d1** [comment]
Thanks for the hint.
