### ISSUE TITLE
How to run in IDEA

### ISSUE THREAD

**Issue by liwei0612** [RMLio/RML-Mapper#28]
I downloaded the source code, how to run in IEDA?

**Comment by ZacharyWhitley** [comment]
It's a maven project so it should recognize this and open as a new project if you open the directory or pom.xml file.

**Comment by pheyvaer** [comment]
@liwei0612 did you manage to get this working?

**Comment by canarvaeza** [comment]
Hi,

I just download the GitHub Source and Make a Maven Install in the RML-Mapper, is this the way to proceed?.
It says Build Success but now i don't know how i should proceed to programm something.

**Comment by pheyvaer** [comment]
@canarvaeza Is it possible to open a separate issue for this?

**Comment by canarvaeza** [comment]
Ok
