### ISSUE TITLE
problem with exec script

### ISSUE THREAD

**Issue by m1ci** [RMLio/RML-Mapper#39]
The line

``
  if [ ! -d "RML-Mapper.jar" ]; then
``

should be fixed to
``
  if [ ! -d "RML-Processor-3.0.2.jar" ]; then
``

otherwise it says:
``
Error: Unable to access jarfile RML-Mapper.jar
``

**Comment by vemonet** [comment]
It has not been fixed apparently. Now it is 
```shell
if [ ! -d "RML-Mapper-v3.0.2.jar" ]; then
```
When it should be **RML-Processor**
```shell
if [ ! -d "RML-Processor-v3.0.2.jar" ]; then
```

**Comment by pheyvaer** [comment]
@vemonet If you have no real need for this specific version of the mapper, we suggest to use the latest version which you can find at a [new repo](https://github.com/RMLio/rmlmapper-java).
