### ISSUE TITLE
RML Processor as a library within a Java Application

### ISSUE THREAD

**Issue by Maatary** [RMLio/RML-Mapper#41]
Hi, 

I wonder if you have any guide on how to use the RML Processor from within a Java application, understood as a library from which we would call a function with input the mapping.

**Comment by canarvaeza** [comment]
Hi,

I published an answer about the topic some time ago.

[](https://github.com/RMLio/RML-Mapper/issues/34)

If you solve it please close this issue.

**Comment by pheyvaer** [comment]
I'll close this because #34 is closed.
