### ISSUE TITLE
Invalid byte 2 of 2-byte UTF-8 sequence

### ISSUE THREAD

**Issue by hujiajia0401** [RMLio/RML-Mapper#43]
hi，i try the mvn clean install to generat the target jar。while i get lots of fetal error below。it‘s seems like some character encoding problem while use the java Xpath。
[Fatal Error] :2:105: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:62: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:62: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:55: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:55: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:55: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:55: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:55: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:71: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:65: An invalid XML character (Unicode: 0x19) was found in the element content of the document.
[Fatal Error] :2:65: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:69: Invalid byte 2 of 4-byte UTF-8 sequence.
[Fatal Error] :2:68: An invalid XML character (Unicode: 0x19) was found in the element content of the document.
[Fatal Error] :2:79: Invalid byte 2 of 4-byte UTF-8 sequence.
[Fatal Error] :2:65: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:77: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:65: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:68: Invalid byte 2 of 4-byte UTF-8 sequence.
[Fatal Error] :2:77: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:75: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:62: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:65: An invalid XML character (Unicode: 0x7) was found in the element content of the document.
[Fatal Error] :2:75: An invalid XML character (Unicode: 0x7) was found in the element content of the document.
[Fatal Error] :2:84: An invalid XML character (Unicode: 0x3) was found in the element content of the document.
[Fatal Error] :2:62: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:55: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:59: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:59: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:65: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:71: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:66: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:66: Invalid byte 2 of 4-byte UTF-8 sequence.
[Fatal Error] :2:71: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:70: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:75: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:63: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:76: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:87: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:87: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:69: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:87: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:61: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:66: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:57: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:59: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:76: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:59: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:66: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:59: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:57: Invalid byte 2 of 4-byte UTF-8 sequence.
[Fatal Error] :2:70: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:69: Invalid byte 2 of 4-byte UTF-8 sequence.
[Fatal Error] :2:59: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:55: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:55: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:55: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:68: Invalid byte 2 of 2-byte UTF-8 sequence.
[Fatal Error] :2:69: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:69: Invalid byte 1 of 1-byte UTF-8 sequence.
[Fatal Error] :2:74: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:59: An invalid XML character (Unicode: 0x7) was found in the element content of the document.
[Fatal Error] :2:65: Invalid byte 2 of 2-byte UTF-8 sequence.
[Fatal Error] :2:66: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:70: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:61: Invalid byte 2 of 2-byte UTF-8 sequence.
[Fatal Error] :2:61: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:68: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:70: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:58: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:56: An invalid XML character (Unicode: 0x1f) was found in the element content of the document.
[Fatal Error] :2:61: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:58: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:90: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:93: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:62: An invalid XML character (Unicode: 0x1) was found in the element content of the document.
[Fatal Error] :2:64: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:62: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:63: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:63: Invalid byte 2 of 4-byte UTF-8 sequence.
[Fatal Error] :2:77: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:77: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:77: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:59: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:57: Invalid byte 2 of 3-byte UTF-8 sequence.
[Fatal Error] :2:60: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:59: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:59: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:59: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:59: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:59: An invalid XML character (Unicode: 0x13) was found in the element content of the document.
[Fatal Error] :2:59: An invalid XML character (Unicode: 0x13) was found in the element content of the document.

**Comment by pheyvaer** [comment]
Did you try the suggestion I gave as a reply to your comment on #40 ?

**Comment by pheyvaer** [comment]
Hi,

We've updated the RMLMapper and it can now be found [here](https://github.com/RMLio/rmlmapper-java). If you have still issues, you can open a new issue at the repo of the new RMLMapper.
