### ISSUE TITLE
Upgrade to RDF4j

### ISSUE THREAD

**Issue by barthanssens** [RMLio/RML-Mapper#6]
Eclipse RDF4j is the new name / project for Sesame (note that RDF4j 2.0, which is equivalent to Sesame 4.1,  requires Java 8). Upgrading would be nice, since the version used by RMLio is relatively old.

**Comment by andimou** [comment]
Idd, I have already upgraded to RDF4J 2.0, but still checking if everything is ok before push public.

To be honest though, I'm a bit concerned regarding Java 8 dependency.

**Comment by barthanssens** [comment]
In that case you could consider using RDF4j 1.0, which is the Java 7 backport of RDF4j 2.0.

The benefit would be that RMLio can stay a little longer on Java 7, while already using the new org.eclipse.rdf4j namespace (and e.g. IRI instead of URI), so this would smoothen the upgrade path a bit.

**Comment by KMax** [comment]
Any progress on this? 

Just FYI:
 - Oracle has ended public support of Java 7 on April 2015 (https://java.com/en/download/faq/java_7.xml),
 - Red Hat ends support of OpenJDK 7 in June 2018.

RML-Mapper is just 2+ years old. Java 8 was released in March 2014. I'm not sure anyone may have a problem with RML-Mapper requiring Java 8.

**Comment by pheyvaer** [comment]
Hi,

We've updated the RMLMapper and it can now be found [here](https://github.com/RMLio/rmlmapper-java). In the new version we use RDF4J.
